apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-proxy-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen {{.Values.proxy.listeningPort}};
        location / {
          proxy_pass {{.Values.destination.scheme}}://{{.Values.destination.service}}.{{.Values.destination.namespace}}.svc.cluster.local:{{.Values.destination.port}};
          {{- if .Values.proxy.hostHeaderEnabled }}
          proxy_set_header Host {{ .Values.proxy.host }};
          {{- end }}
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /websocket {
          proxy_pass {{.Values.destination.scheme}}://{{.Values.destination.service}}.{{.Values.destination.namespace}}.svc.cluster.local:{{.Values.destination.port}};
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          {{- if .Values.proxy.hostHeaderEnabled }}
          proxy_set_header Host {{ .Values.proxy.host }};
          {{- end }}
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
    }
