{{- if .Values.autoscaling.enabled}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: keycloak-proxy-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: keycloak-proxy
  minReplicas: {{.Values.autoscaling.minReplicas}}
  maxReplicas: {{.Values.autoscaling.maxReplicas}}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{.Values.autoscaling.targetCPUUtilizationPercentage}}
{{- end}}
