apiVersion: v1
kind: Service
metadata:
  name: keycloak-proxy
spec:
  selector:
    app: nginx-proxy
  ports:
    - protocol: TCP
      port: {{.Values.proxy.servicePort}}
      targetPort: {{.Values.proxy.listeningPort}}
  type: ClusterIP
